"""build.py — full course build.

1. Splice seed data into player   (/* DATA:BEGIN */ ... /* DATA:END */)
2. Splice engine files            (/* ENGINES:BEGIN */ ... /* ENGINES:END */)
3. Splice trace JSONs             (/* TRACES:BEGIN */ ... /* TRACES:END */)
4. Inject all module fragments    (via inject.py)
5. Extract every <script> block -> node --check each
6. Emit docs/PROGRESS.md (status table + coverage report)

Windows-friendly: pathlib only, no shell-isms.
"""
import json
import re
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLAYER = ROOT / "player" / "index.html"
ENGINES = [ROOT / "engine" / n for n in
           ("sqlrunner.js", "sparksim.js", "traceplayer.js", "pyrunner.js")]
TRACES = ROOT / "engine" / "traces"
MODULES = ROOT / "content" / "modules"
SEED = ROOT / "data" / "nimbusmart" / "seed.js"

sys.path.insert(0, str(ROOT / "scripts"))
import inject as inj  # noqa: E402

TITLES = {}  # filled from fragments for PROGRESS.md


def splice_region(src: str, name: str, payload: str) -> str:
    begin, end = f"/* {name}:BEGIN */", f"/* {name}:END */"
    i, j = src.index(begin) + len(begin), src.index(end)
    return src[:i] + "\n" + payload + "\n" + src[j:]


def build_player():
    src = PLAYER.read_text(encoding="utf-8")

    src = splice_region(src, "DATA", SEED.read_text(encoding="utf-8").strip())

    engine_js = []
    for e in ENGINES:
        if e.exists():
            engine_js.append(f"/* ---- {e.name} ---- */\n" + e.read_text(encoding="utf-8").strip())
        else:
            print(f"  note: engine missing, skipped: {e.name}")
    src = splice_region(src, "ENGINES", "\n".join(engine_js))

    traces = {}
    for t in sorted(TRACES.glob("*.json")):
        if t.name == "schema.json":
            continue
        traces[t.stem] = json.loads(t.read_text(encoding="utf-8"))
    src = splice_region(src, "TRACES",
                        "window.TRACES = " + json.dumps(traces, separators=(",", ":")) + ";")

    PLAYER.write_text(src, encoding="utf-8")
    print(f"player assembled: data + {len(engine_js)} engines + {len(traces)} traces")


def inject_all():
    ids = [p.stem for p in sorted(MODULES.glob("[A-H]*.js")) if p.stem in inj.CANONICAL]
    if ids:
        inj.inject(ids)
    return ids


def node_check() -> bool:
    src = PLAYER.read_text(encoding="utf-8")
    blocks = re.findall(r"<script>(.*?)</script>", src, re.S)
    ok = True
    with tempfile.TemporaryDirectory() as td:
        for i, b in enumerate(blocks):
            f = Path(td) / f"block{i}.js"
            f.write_text(b, encoding="utf-8")
            r = subprocess.run(["node", "--check", str(f)],
                               capture_output=True, text=True, encoding="utf-8")
            if r.returncode != 0:
                ok = False
                print(f"[FAIL] script block {i}: {r.stderr.strip()[:500]}")
    print(f"node --check: {len(blocks)} script block(s) {'PASS' if ok else 'FAIL'}")
    return ok


def progress(ids):
    import validate as val
    rows, coverage = [], []
    for mid in inj.CANONICAL:
        p = MODULES / f"{mid}.js"
        if not p.exists():
            rows.append((mid, "—", "missing", ""))
            continue
        errors, warnings = val.validate(p, final=False)
        mod, _ = val.load_fragment(p)
        title = mod["title"] if mod else "?"
        status = "verified" if not errors and not warnings else ("draft" if errors else "injected")
        note = "; ".join(errors[:2] + warnings[:2])
        rows.append((mid, title, status, note[:90]))
        if mod:
            missing = []
            types = [s.get("type") for s in mod.get("concept", [])]
            if "analogy" not in types:
                missing.append("analogy")
            if "javaBridge" not in types:
                missing.append("javaBridge")
            if not mod.get("lab", {}).get("understand"):
                missing.append("lab:understand")
            if not mod.get("lab", {}).get("buildWithAI"):
                missing.append("lab:buildWithAI")
            if not (3 <= len(mod.get("check", [])) <= 5):
                missing.append("checks")
            if missing:
                coverage.append(f"- {mid}: missing {', '.join(missing)}")

    lines = [f"# Progress — generated by build.py on {date.today().isoformat()}", "",
             "| Module | Title | Status | Notes |", "|---|---|---|---|"]
    lines += [f"| {m} | {t} | {s} | {n} |" for m, t, s, n in rows]
    lines += ["", "## Coverage gaps", ""] + (coverage or ["(none)"])
    done = sum(1 for r in rows if r[2] in ("verified", "injected"))
    lines += ["", f"**{done}/{len(inj.CANONICAL)} modules present.**"]
    (ROOT / "docs" / "PROGRESS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"PROGRESS.md: {done}/{len(inj.CANONICAL)} modules present, {len(coverage)} coverage gap(s)")


if __name__ == "__main__":
    build_player()
    ids = inject_all()
    ok = node_check()
    progress(ids)
    size = PLAYER.stat().st_size
    print(f"player/index.html: {size:,} bytes")
    sys.exit(0 if ok else 1)
